name: React app deploy to surge
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - uses: borales/actions-yarn@2.0.0
      with:
          cmd: install
    - name: Build react app
      run: yarn build

    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to surge
      run: surge ./build https://sid24.surge.sh/ ${{ secrets.SURGE_TOKEN }}
