name: React app deploy to surge
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.17
    
    - name: install lateste yarn
      run: corepack prepare yarn@stable --activate
    - name: Activate Latest yarn
      run: yarn set version stable

    - name: Build react app
      run: yarn build

    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to surge
      run: surge ./build https://sid24.surge.sh/ ${{ secrets.SURGE_TOKEN }}
